package dev.usbharu.hideout.activitystreams

object Properties {
    const val ID = "@id"
    const val TYPE = "@type"
    const val VALUE = "@value"
    const val LANGUAGE = "@language"
    const val ACTOR = "https://www.w3.org/ns/activitystreams#actor"
    const val OBJECT = "https://www.w3.org/ns/activitystreams#object"
    const val CONTENT = "https://www.w3.org/ns/activitystreams#content"
    const val NAME = "https://www.w3.org/ns/activitystreams#name"
    const val PUBLISHED = "https://www.w3.org/ns/activitystreams#published"
    const val ATTACHMENT = "https://www.w3.org/ns/activitystreams#attachment"
    const val ATTRIBUTED_TO = "https://www.w3.org/ns/activitystreams#attributedTo"
    const val AUDIENCE = "https://www.w3.org/ns/activitystreams#audience"
    const val BCC = "https://www.w3.org/ns/activitystreams#bcc"
    const val BTO = "https://www.w3.org/ns/activitystreams#bto"
    const val CC = "https://www.w3.org/ns/activitystreams#cc"
    const val CONTEXT = "https://www.w3.org/ns/activitystreams#context"
    const val CURRENT = "https://www.w3.org/ns/activitystreams#current"
    const val FIRST = "https://www.w3.org/ns/activitystreams#first"
    const val LAST = "https://www.w3.org/ns/activitystreams#last"
    const val GENERATOR = "https://www.w3.org/ns/activitystreams#generator"
    const val ICON = "https://www.w3.org/ns/activitystreams#icon"
    const val IMAGE = "https://www.w3.org/ns/activitystreams#image"
    const val IN_REPLY_TO = "https://www.w3.org/ns/activitystreams#inReplyTo"
    const val INSTRUMENT = "https://www.w3.org/ns/activitystreams#instrument"
    const val LOCATION = "https://www.w3.org/ns/activitystreams#location"
    const val ITEMS = "https://www.w3.org/ns/activitystreams#items"
    const val ONE_OF = "http://www.w3.org/ns/activitystreams#oneOf"
    const val ANY_OF = "http://www.w3.org/ns/activitystreams#anyOf"
    const val CLOSED = "http://www.w3.org/ns/activitystreams#closed"
    const val ORIGIN = "http://www.w3.org/ns/activitystreams#origin"
    const val NEXT = "http://www.w3.org/ns/activitystreams#next"
    const val PREV = "http://www.w3.org/ns/activitystreams#prev"
    const val PREVIEW = "http://www.w3.org/ns/activitystreams#preview"
    const val RESULT = "http://www.w3.org/ns/activitystreams#result"
    const val REPLIES = "http://www.w3.org/ns/activitystreams#replies"
    const val TAG = "http://www.w3.org/ns/activitystreams#tag"
    const val TARGET = "http://www.w3.org/ns/activitystreams#target"
    const val TO = "http://www.w3.org/ns/activitystreams#to"
    const val URL = "https://www.w3.org/ns/activitystreams#url"
    const val ACCURACY = "https://www.w3.org/ns/activitystreams#accurency"
    const val ALTITUDE = "https://www.w3.org/ns/activitystreams#altitude"
    const val DURATION = "https://www.w3.org/ns/activitystreams#duration"
    const val HEIGHT = "https://www.w3.org/ns/activitystreams#height"
    const val WIDTH = "https://www.w3.org/ns/activitystreams#width"
    const val HREF = "https://www.w3.org/ns/activitystreams#href"
    const val HREFLANG = "https://www.w3.org/ns/activitystreams#hreflang"
    const val PART_OF = "https://www.w3.org/ns/activitystreams#partOf"
    const val LATITUDE = "https://www.w3.org/ns/activitystreams#latitute"
    const val LONGITUDE = "https://www.w3.org/ns/activitystreams#longitute"
    const val MEDIA_TYPE = "https://www.w3.org/ns/activitystreams#mediaType"
    const val END_TIME = "https://www.w3.org/ns/activitystreams#endTime"
    const val START_TIME = "https://www.w3.org/ns/activitystreams#startTime"
    const val RADIUS = "https://www.w3.org/ns/activitystreams#radius"
    const val REL = "https://www.w3.org/ns/activitystreams#rel"
    const val START_INDEX = "https://www.w3.org/ns/activitystreams#startIndex"
    const val SUMMARY = "https://www.w3.org/ns/activitystreams#summary"
    const val TOTAL_ITEMS = "https://www.w3.org/ns/activitystreams#totalItems"
    const val UNITS = "https://www.w3.org/ns/activitystreams#units"
    const val UPDATED = "https://www.w3.org/ns/activitystreams#updated"
    const val SUBJECT = "https://www.w3.org/ns/activitystreams#subject"
    const val RELATIONSHIP = "https://www.w3.org/ns/activitystreams#relationship"
    const val DESCRIBES = "https://www.w3.org/ns/activitystreams#describes"
    const val FORMER_TYPE = "https://www.w3.org/ns/activitystreams#formerType"
    const val DELETED = "https://www.w3.org/ns/activitystreams#deleted"
}

object Type {
    const val LINK = "https://www.w3.org/ns/activitystreams#Link"
    const val NOTE = "https://www.w3.org/ns/activitystreams#Note"
    const val ACCEPT = "https://www.w3.org/ns/activitystreams#Accept"
    const val TENTATIVE_ACCEPT = "https://www.w3.org/ns/activitystreams#TentativeAccept"
    const val ADD = "https://www.w3.org/ns/activitystreams#Add"
    const val ARRIVE = "https://www.w3.org/ns/activitystreams#Arrive"
}